Exercise classification: Type Hint Fix in AdaBoost
FAU-CS6/KDD pull request #74
Opened 2023-06-30 06:34 UTC by dominik-probst

During yesterday's exercise we noticed that the type hints in _misclassification_error do not match the sample solution. 

Please review @melsigl

2023-06-30 09:31 UTC, melsigl commented
Thanks for fixing the type hint! Although, this PR contains two commits, one of which is already merged. See commit 38a5b1fcff6bc100b88cbb82c40c9318364f0b23 which fixes typos. This commit is already merged with PR #72. 
Please fix this current PR such that it only contains the newest commit.

2023-06-30 12:52 UTC, melsigl requested changes
Please remove the commit concerning these files as these changes are already merged with PR #72 .

2023-06-30 14:39 UTC, dominik-probst commented
Done

2023-07-03 09:54 UTC, melsigl approved these changes

2023-07-03 09:54 UTC, merged